# Copy the id_rsa.pub file from the machine running this command to the remote hosts
- hosts: all
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        # Use the 'ansible_user' variable defined in the inventory file
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
