# Copy the local id_rsa.pub to the remote machines
- hosts: all
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        # Use the 'ansible_user' variable defined in the inventory file
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', './id_rsa.pub') }}"
